# .github/actions/execute-action/action.yml

name: "Execute Work and Python Script"
description: "Runs work.sh to fetch workflow info and script.py to generate output.csv, then uploads both as artifacts."
inputs:
  my_input:
    description: "An input argument for the action"
    required: true
runs:
  using: "composite"
  steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: vmilosevic/actions
        path: ${GITHUB_ACTION_PATH}

    - name: Debug log
      shell: bash
      run: |
        set -o xtrace
        pwd
        echo GITHUB_ACTION_PATH = ${GITHUB_ACTION_PATH}
        ls -la
        ls -la ${GITHUB_ACTION_PATH}
    - name: Run work.sh
      shell: bash
      run: |
        chmod +x ${GITHUB_ACTION_PATH}/work.sh
        ${GITHUB_ACTION_PATH}/work.sh "${{ inputs.my_input }}"
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Run script.py
      shell: bash
      run: |
        python3 ${GITHUB_ACTION_PATH}/script.py

    - name: Debug log
      shell: bash
      run: |
        set -x

    - name: Upload output.json
      uses: actions/upload-artifact@v4
      with:
        name: output-json
        path: ./output.json

    - name: Upload output.csv
      uses: actions/upload-artifact@v4
      with:
        name: output-csv
        path: ./output.csv
