# .github/workflows/main.yml

name: Main workflow

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  test-execute-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run custom execute action
        uses: ./.github/actions/generic
        with:
          my_input: "Lorme_ipsum"
