name: "[internal] Produce analytic data"

on:
  workflow_run:
    workflows: # List workflow that we want to collect data for
      - "Main workflow"
      - "Test Collect Data Action"
    types:
      - completed

jobs:
  produce-cicd-data:
    runs-on: ubuntu-latest
    steps:
      - name: Upload cicd data
        uses: ./.github/actions/collect_data
        # if: ${{ github.event_name == 'workflow_run' }}
        with:
          repository: ${{ github.event.workflow_run.repository }}
          run_id: ${{ github.event.workflow_run.run_id }}
          run_attempt: ${{ github.event.workflow_run.run_attempt }}
          GH_TOKEN: ${{ github.token }}