name: "[internal] Collect workflow data"

on:
  workflow_run:
    workflows: # List workflow that we want to collect data for
      - "Main workflow"
      - "Test Collect Data Action"
    types:
      - completed

jobs:
  produce-cicd-data:
    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ github.token }}
    steps:

      - name: Checkout code # Only needed for testing action in same repo
        uses: actions/checkout@v4

      - name: Debug
        shell: bash
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Workflow run repository: ${{ github.event.workflow_run.id }}"
          echo "Workflow run run_attempt: ${{ github.event.workflow_run.run_attempt }}"

      - name: Collect CI/CD data
        uses: ./.github/actions/collect_data
        if: ${{ github.event_name == 'workflow_run' }}
        with:
          repository: ${{ github.repository }}
          run_id: ${{ github.event.workflow_run.id }}
          run_attempt: ${{ github.event.workflow_run.run_attempt }}
          # GH_TOKEN: ${{ github.token }}
