name: "[internal] Collect data for: ${{ github.event.workflow_run.name }}"

on:
  workflow_run:
    workflows: # List workflow that we want to collect data for
      - "Main workflow"
      - "Test Collect Data Action"
    types:
      - completed

jobs:
  produce-cicd-data:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code # Only needed for testing action in same repo
        uses: actions/checkout@v4

      - name: Collect CI/CD data
        uses: ./.github/actions/collect_data
        # if: ${{ github.event_name == 'workflow_run' }}
        with:
          repository: ${{ github.event.workflow_run.repository }}
          run_id: ${{ github.event.workflow_run.run_id }}
          run_attempt: ${{ github.event.workflow_run.run_attempt }}
          GH_TOKEN: ${{ github.token }}